/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module top(clk, reset, result, flag_gt_zero);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input clk;
  wire clk;
  output flag_gt_zero;
  wire flag_gt_zero;
  wire \fsm.nstate[0] ;
  wire \fsm.nstate[1] ;
  wire \fsm.nstate[2] ;
  wire \fsm.pstate[0] ;
  wire \fsm.pstate[1] ;
  wire \fsm.pstate[2] ;
  input reset;
  wire reset;
  output [6:0] result;
  wire [6:0] result;
  sky130_fd_sc_hd__inv_2 _09_ (
    .A(\fsm.pstate[1] ),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand2b_4 _10_ (
    .A_N(\fsm.pstate[2] ),
    .B(\fsm.pstate[0] ),
    .Y(_04_)
  );
  sky130_fd_sc_hd__buf_6 _11_ (
    .A(_04_),
    .X(result[0])
  );
  sky130_fd_sc_hd__or2_4 _12_ (
    .A(_03_),
    .B(result[0]),
    .X(_05_)
  );
  sky130_fd_sc_hd__buf_6 _13_ (
    .A(_05_),
    .X(flag_gt_zero)
  );
  sky130_fd_sc_hd__o21bai_2 _14_ (
    .A1(\fsm.pstate[0] ),
    .A2(\fsm.pstate[1] ),
    .B1_N(\fsm.pstate[2] ),
    .Y(result[6])
  );
  sky130_fd_sc_hd__or2_2 _15_ (
    .A(_03_),
    .B(\fsm.pstate[2] ),
    .X(_06_)
  );
  sky130_fd_sc_hd__buf_1 _16_ (
    .A(_06_),
    .X(result[3])
  );
  sky130_fd_sc_hd__or2b_2 _17_ (
    .A(\fsm.pstate[2] ),
    .B_N(\fsm.pstate[0] ),
    .X(_07_)
  );
  sky130_fd_sc_hd__buf_1 _18_ (
    .A(_07_),
    .X(result[4])
  );
  sky130_fd_sc_hd__nor2_2 _19_ (
    .A(\fsm.pstate[0] ),
    .B(\fsm.pstate[2] ),
    .Y(\fsm.nstate[0] )
  );
  sky130_fd_sc_hd__xnor2_2 _20_ (
    .A(\fsm.pstate[0] ),
    .B(\fsm.pstate[1] ),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_2 _21_ (
    .A(\fsm.pstate[2] ),
    .B(_08_),
    .Y(\fsm.nstate[1] )
  );
  sky130_fd_sc_hd__nor2_2 _22_ (
    .A(_03_),
    .B(result[0]),
    .Y(\fsm.nstate[2] )
  );
  sky130_fd_sc_hd__inv_2 _23_ (
    .A(reset),
    .Y(_00_)
  );
  sky130_fd_sc_hd__inv_2 _24_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__inv_2 _25_ (
    .A(reset),
    .Y(_02_)
  );
  sky130_fd_sc_hd__dfrtp_2 _26_ (
    .CLK(clk),
    .D(\fsm.nstate[0] ),
    .Q(\fsm.pstate[0] ),
    .RESET_B(_00_)
  );
  sky130_fd_sc_hd__dfrtp_2 _27_ (
    .CLK(clk),
    .D(\fsm.nstate[1] ),
    .Q(\fsm.pstate[1] ),
    .RESET_B(_01_)
  );
  sky130_fd_sc_hd__dfrtp_2 _28_ (
    .CLK(clk),
    .D(\fsm.nstate[2] ),
    .Q(\fsm.pstate[2] ),
    .RESET_B(_02_)
  );
  sky130_fd_sc_hd__buf_2 _29_ (
    .A(flag_gt_zero),
    .X(result[1])
  );
  sky130_fd_sc_hd__buf_2 _30_ (
    .A(result[6]),
    .X(result[2])
  );
  sky130_fd_sc_hd__buf_2 _31_ (
    .A(flag_gt_zero),
    .X(result[5])
  );
endmodule
