/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module top(clk, reset, result, flag_gt_zero);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input clk;
  wire clk;
  wire \controller_inst.nstate[0] ;
  wire \controller_inst.nstate[1] ;
  wire \controller_inst.pstate[0] ;
  wire \controller_inst.pstate[1] ;
  output flag_gt_zero;
  wire flag_gt_zero;
  input reset;
  wire reset;
  output [6:0] result;
  wire [6:0] result;
  sky130_fd_sc_hd__xnor2_4 _04_ (
    .A(\controller_inst.pstate[1] ),
    .B(\controller_inst.pstate[0] ),
    .Y(result[4])
  );
  sky130_fd_sc_hd__nand2b_4 _05_ (
    .A_N(\controller_inst.pstate[0] ),
    .B(\controller_inst.pstate[1] ),
    .Y(_02_)
  );
  sky130_fd_sc_hd__buf_6 _06_ (
    .A(_02_),
    .X(result[5])
  );
  sky130_fd_sc_hd__nand2b_4 _07_ (
    .A_N(\controller_inst.pstate[1] ),
    .B(\controller_inst.pstate[0] ),
    .Y(_03_)
  );
  sky130_fd_sc_hd__buf_6 _08_ (
    .A(_03_),
    .X(result[2])
  );
  sky130_fd_sc_hd__xnor2_4 _09_ (
    .A(\controller_inst.pstate[1] ),
    .B(\controller_inst.pstate[0] ),
    .Y(result[6])
  );
  sky130_fd_sc_hd__inv_2 _10_ (
    .A(\controller_inst.pstate[0] ),
    .Y(\controller_inst.nstate[0] )
  );
  sky130_fd_sc_hd__xor2_4 _11_ (
    .A(\controller_inst.pstate[1] ),
    .B(\controller_inst.pstate[0] ),
    .X(\controller_inst.nstate[1] )
  );
  sky130_fd_sc_hd__inv_2 _12_ (
    .A(reset),
    .Y(_00_)
  );
  sky130_fd_sc_hd__inv_2 _13_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__dfrtp_2 _14_ (
    .CLK(clk),
    .D(\controller_inst.nstate[0] ),
    .Q(\controller_inst.pstate[0] ),
    .RESET_B(_00_)
  );
  sky130_fd_sc_hd__dfrtp_2 _15_ (
    .CLK(clk),
    .D(\controller_inst.nstate[1] ),
    .Q(\controller_inst.pstate[1] ),
    .RESET_B(_01_)
  );
  sky130_fd_sc_hd__conb_1 _16_ (
    .HI(flag_gt_zero)
  );
  sky130_fd_sc_hd__conb_1 _17_ (
    .HI(result[3])
  );
  sky130_fd_sc_hd__buf_2 _18_ (
    .A(result[4]),
    .X(result[0])
  );
  sky130_fd_sc_hd__buf_2 _19_ (
    .A(result[5]),
    .X(result[1])
  );
endmodule
