/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module ALU_7bit(A, B, OP, result, ZF);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  input [6:0] A;
  wire [6:0] A;
  input [6:0] B;
  wire [6:0] B;
  input OP;
  wire OP;
  output ZF;
  wire ZF;
  output [6:0] result;
  wire [6:0] result;
  sky130_fd_sc_hd__inv_2 _38_ (
    .A(OP),
    .Y(_00_)
  );
  sky130_fd_sc_hd__inv_2 _39_ (
    .A(B[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and2b_2 _40_ (
    .A_N(B[0]),
    .B(A[2]),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_2 _41_ (
    .A0(A[4]),
    .A1(A[5]),
    .S(B[0]),
    .X(_03_)
  );
  sky130_fd_sc_hd__or3b_2 _42_ (
    .A(B[2]),
    .B(A[1]),
    .C_N(B[0]),
    .X(_04_)
  );
  sky130_fd_sc_hd__inv_2 _43_ (
    .A(B[1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__o211a_2 _44_ (
    .A1(_01_),
    .A2(_03_),
    .B1(_04_),
    .C1(_05_),
    .X(_06_)
  );
  sky130_fd_sc_hd__and2b_2 _45_ (
    .A_N(B[0]),
    .B(A[6]),
    .X(_07_)
  );
  sky130_fd_sc_hd__and4b_2 _46_ (
    .A_N(B[2]),
    .B(B[0]),
    .C(A[3]),
    .D(B[1]),
    .X(_08_)
  );
  sky130_fd_sc_hd__a31o_2 _47_ (
    .A1(B[1]),
    .A2(B[2]),
    .A3(_07_),
    .B1(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__a211o_2 _48_ (
    .A1(_01_),
    .A2(_02_),
    .B1(_06_),
    .C1(_09_),
    .X(_10_)
  );
  sky130_fd_sc_hd__nor2_2 _49_ (
    .A(B[1]),
    .B(B[2]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__or3b_2 _50_ (
    .A(B[0]),
    .B(_00_),
    .C_N(_11_),
    .X(_12_)
  );
  sky130_fd_sc_hd__mux2_2 _51_ (
    .A0(_12_),
    .A1(OP),
    .S(A[0]),
    .X(_13_)
  );
  sky130_fd_sc_hd__o21a_4 _52_ (
    .A1(_00_),
    .A2(_10_),
    .B1(_13_),
    .X(result[0])
  );
  sky130_fd_sc_hd__mux2_2 _53_ (
    .A0(A[2]),
    .A1(A[6]),
    .S(B[2]),
    .X(_14_)
  );
  sky130_fd_sc_hd__and2_2 _54_ (
    .A(_05_),
    .B(_14_),
    .X(_15_)
  );
  sky130_fd_sc_hd__inv_2 _55_ (
    .A(B[0]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__a311o_2 _56_ (
    .A1(B[1]),
    .A2(_01_),
    .A3(A[4]),
    .B1(_15_),
    .C1(_16_),
    .X(_17_)
  );
  sky130_fd_sc_hd__mux2_2 _57_ (
    .A0(_12_),
    .A1(OP),
    .S(A[1]),
    .X(_18_)
  );
  sky130_fd_sc_hd__and2b_2 _58_ (
    .A_N(B[2]),
    .B(A[3]),
    .X(_19_)
  );
  sky130_fd_sc_hd__o22a_2 _59_ (
    .A1(_01_),
    .A2(A[5]),
    .B1(_19_),
    .B2(_05_),
    .X(_20_)
  );
  sky130_fd_sc_hd__or3_2 _60_ (
    .A(B[0]),
    .B(_00_),
    .C(_20_),
    .X(_21_)
  );
  sky130_fd_sc_hd__o211a_4 _61_ (
    .A1(_00_),
    .A2(_17_),
    .B1(_18_),
    .C1(_21_),
    .X(result[1])
  );
  sky130_fd_sc_hd__inv_2 _62_ (
    .A(A[2]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a211o_2 _63_ (
    .A1(B[0]),
    .A2(A[3]),
    .B1(_02_),
    .C1(B[2]),
    .X(_23_)
  );
  sky130_fd_sc_hd__o2111a_2 _64_ (
    .A1(_01_),
    .A2(_07_),
    .B1(_23_),
    .C1(OP),
    .D1(_05_),
    .X(_24_)
  );
  sky130_fd_sc_hd__and2b_2 _65_ (
    .A_N(B[2]),
    .B(OP),
    .X(_25_)
  );
  sky130_fd_sc_hd__o211a_2 _66_ (
    .A1(B[1]),
    .A2(_02_),
    .B1(_03_),
    .C1(_25_),
    .X(_26_)
  );
  sky130_fd_sc_hd__a211o_2 _67_ (
    .A1(_22_),
    .A2(_00_),
    .B1(_24_),
    .C1(_26_),
    .X(result[2])
  );
  sky130_fd_sc_hd__mux4_2 _68_ (
    .A0(A[3]),
    .A1(A[4]),
    .A2(A[5]),
    .A3(A[6]),
    .S0(B[0]),
    .S1(B[1]),
    .X(_27_)
  );
  sky130_fd_sc_hd__a2bb2o_4 _69_ (
    .A1_N(A[3]),
    .A2_N(OP),
    .B1(_25_),
    .B2(_27_),
    .X(result[3])
  );
  sky130_fd_sc_hd__or3_4 _70_ (
    .A(B[1]),
    .B(B[0]),
    .C(A[4]),
    .X(_28_)
  );
  sky130_fd_sc_hd__o21a_2 _71_ (
    .A1(_05_),
    .A2(_07_),
    .B1(_28_),
    .X(_29_)
  );
  sky130_fd_sc_hd__o21a_2 _72_ (
    .A1(_16_),
    .A2(A[5]),
    .B1(_25_),
    .X(_30_)
  );
  sky130_fd_sc_hd__a2bb2o_4 _73_ (
    .A1_N(A[4]),
    .A2_N(OP),
    .B1(_29_),
    .B2(_30_),
    .X(result[4])
  );
  sky130_fd_sc_hd__and2_2 _74_ (
    .A(_16_),
    .B(A[5]),
    .X(_31_)
  );
  sky130_fd_sc_hd__a21o_2 _75_ (
    .A1(B[0]),
    .A2(A[6]),
    .B1(_31_),
    .X(_32_)
  );
  sky130_fd_sc_hd__nor2_2 _76_ (
    .A(A[5]),
    .B(OP),
    .Y(_33_)
  );
  sky130_fd_sc_hd__a31o_2 _77_ (
    .A1(OP),
    .A2(_11_),
    .A3(_32_),
    .B1(_33_),
    .X(result[5])
  );
  sky130_fd_sc_hd__mux2_2 _78_ (
    .A0(OP),
    .A1(_12_),
    .S(A[6]),
    .X(_34_)
  );
  sky130_fd_sc_hd__inv_2 _79_ (
    .A(_34_),
    .Y(result[6])
  );
  sky130_fd_sc_hd__a21oi_2 _80_ (
    .A1(A[6]),
    .A2(A[5]),
    .B1(OP),
    .Y(_35_)
  );
  sky130_fd_sc_hd__o211a_2 _81_ (
    .A1(A[6]),
    .A2(_31_),
    .B1(_11_),
    .C1(OP),
    .X(_36_)
  );
  sky130_fd_sc_hd__or4_4 _82_ (
    .A(result[3]),
    .B(result[4]),
    .C(_35_),
    .D(_36_),
    .X(_37_)
  );
  sky130_fd_sc_hd__nor4_4 _83_ (
    .A(result[0]),
    .B(result[1]),
    .C(result[2]),
    .D(_37_),
    .Y(ZF)
  );
endmodule
